### ISSUE TITLE
mpflash list (1.24.7) now fails to list any board

### ISSUE THREAD

**Issue by scruss** [Josverl/mpflash#18]
Recently reinstalled via pipx on Python 3.12.7 (Ubuntu):

```
mpflash list
17:30:00 | ⚠️ Traceback (most recent call last):

17:30:00 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:00 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:00 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:00 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:00 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:00 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:00 | ⚠️     from . import _adapters, _meta

17:30:00 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:00 | ⚠️     import email.message

17:30:00 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:00 | ⚠️     from email import utils

17:30:00 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:00 | ⚠️     from email._parseaddr import quote

17:30:00 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:00 | ⚠️     import time, calendar

17:30:00 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:00 | ⚠️     class _localized_month:

17:30:00 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:00 | ⚠️     _months = 

17:30:00 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:00 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

⠋ Scanning ttyACM0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0117:30:01 | ⚠️ Traceback (most recent call last):

17:30:01 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:01 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:01 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:01 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:01 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:01 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:01 | ⚠️     from . import _adapters, _meta

17:30:01 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:01 | ⚠️     import email.message

17:30:01 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:01 | ⚠️     from email import utils

17:30:01 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:01 | ⚠️     from email._parseaddr import quote

17:30:01 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:01 | ⚠️     import time, calendar

17:30:01 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:01 | ⚠️     class _localized_month:

17:30:01 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:01 | ⚠️     _months = 

17:30:01 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:01 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

⠹ Scanning ttyACM0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0217:30:02 | ⚠️ Traceback (most recent call last):

17:30:02 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:02 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:02 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:02 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:02 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:02 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:02 | ⚠️     from . import _adapters, _meta

17:30:02 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:02 | ⚠️     import email.message

17:30:02 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:02 | ⚠️     from email import utils

17:30:02 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:02 | ⚠️     from email._parseaddr import quote

17:30:02 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:02 | ⚠️     import time, calendar

17:30:02 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:02 | ⚠️     class _localized_month:

17:30:02 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:02 | ⚠️     _months = 

17:30:02 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:02 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

Error: Failed to get mcu_info for /dev/ttyACM0
⠹ Scanning ttyACM0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0217:30:02 | ⚠️ Traceback (most recent call last):

17:30:02 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:02 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:02 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:02 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:02 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:02 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:02 | ⚠️     from . import _adapters, _meta

17:30:02 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:02 | ⚠️     import email.message

17:30:02 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:02 | ⚠️     from email import utils

17:30:02 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:02 | ⚠️     from email._parseaddr import quote

17:30:02 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:02 | ⚠️     import time, calendar

17:30:02 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:02 | ⚠️     class _localized_month:

17:30:02 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:02 | ⚠️     _months = 

17:30:02 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:02 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

⠴ Scanning ttyACM1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0317:30:03 | ⚠️ Traceback (most recent call last):

17:30:03 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:03 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:03 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:03 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:03 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:03 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:03 | ⚠️     from . import _adapters, _meta

17:30:03 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:03 | ⚠️     import email.message

17:30:03 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:03 | ⚠️     from email import utils

17:30:03 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:03 | ⚠️     from email._parseaddr import quote

17:30:03 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:03 | ⚠️     import time, calendar

17:30:03 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:03 | ⚠️     class _localized_month:

17:30:03 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:03 | ⚠️     _months = 

17:30:03 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:03 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

⠧ Scanning ttyACM1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0417:30:04 | ⚠️ Traceback (most recent call last):

17:30:04 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:04 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:04 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:04 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:04 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:04 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:04 | ⚠️     from . import _adapters, _meta

17:30:04 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:04 | ⚠️     import email.message

17:30:04 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:04 | ⚠️     from email import utils

17:30:04 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:04 | ⚠️     from email._parseaddr import quote

17:30:04 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:04 | ⚠️     import time, calendar

17:30:04 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:04 | ⚠️     class _localized_month:

17:30:04 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:04 | ⚠️     _months = 

17:30:04 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:04 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

Error: Failed to get mcu_info for /dev/ttyACM1
⠧ Scanning ttyACM1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0417:30:05 | ⚠️ Traceback (most recent call last):

17:30:05 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:05 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:05 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:05 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:05 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:05 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:05 | ⚠️     from . import _adapters, _meta

17:30:05 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:05 | ⚠️     import email.message

17:30:05 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:05 | ⚠️     from email import utils

17:30:05 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:05 | ⚠️     from email._parseaddr import quote

17:30:05 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:05 | ⚠️     import time, calendar

17:30:05 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:05 | ⚠️     class _localized_month:

17:30:05 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:05 | ⚠️     _months = 

17:30:05 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:05 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

⠋ Scanning ttyUSB1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0517:30:06 | ⚠️ Traceback (most recent call last):

17:30:06 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:06 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:06 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:06 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:06 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:06 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:06 | ⚠️     from . import _adapters, _meta

17:30:06 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:06 | ⚠️     import email.message

17:30:06 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:06 | ⚠️     from email import utils

17:30:06 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:06 | ⚠️     from email._parseaddr import quote

17:30:06 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:06 | ⚠️     import time, calendar

17:30:06 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:06 | ⚠️     class _localized_month:

17:30:06 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:06 | ⚠️     _months = 

17:30:06 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:06 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

⠹ Scanning ttyUSB1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:0617:30:07 | ⚠️ Traceback (most recent call last):

17:30:07 | ⚠️   File "<frozen runpy>", line 189, in _run_module_as_main

17:30:07 | ⚠️   File "<frozen runpy>", line 148, in _get_module_details

17:30:07 | ⚠️   File "<frozen runpy>", line 112, in _get_module_details

17:30:07 | ⚠️   File 
"/home/scruss/.local/pipx/venvs/mpflash/lib/python3.12/site-packages/mpremote/__
init__.py", line 2, in <module>

17:30:07 | ⚠️     from importlib.metadata import version, PackageNotFoundError

17:30:07 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 
19, in <module>

17:30:07 | ⚠️     from . import _adapters, _meta

17:30:07 | ⚠️   File "/usr/lib/python3.12/importlib/metadata/_adapters.py", line
5, in <module>

17:30:07 | ⚠️     import email.message

17:30:07 | ⚠️   File "/usr/lib/python3.12/email/message.py", line 15, in <module>

17:30:07 | ⚠️     from email import utils

17:30:07 | ⚠️   File "/usr/lib/python3.12/email/utils.py", line 33, in <module>

17:30:07 | ⚠️     from email._parseaddr import quote

17:30:07 | ⚠️   File "/usr/lib/python3.12/email/_parseaddr.py", line 16, in 
<module>

17:30:07 | ⚠️     import time, calendar

17:30:07 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 94, in <module>

17:30:07 | ⚠️     class _localized_month:

17:30:07 | ⚠️   File "/usr/lib/python3.12/calendar.py", line 96, in 
_localized_month

17:30:07 | ⚠️     _months = 

17:30:07 | ⚠️                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

17:30:07 | ⚠️ AttributeError: 'date' object has no attribute 'strftime'

Error: Failed to get mcu_info for /dev/ttyUSB1

      Connected boards      
┏━━━━━━━┳━━━━┳━━━━━┳━━━━━━━┓
┃Ser.   ┃Fam.┃Board┃Version┃
┡━━━━━━━╇━━━━╇━━━━━╇━━━━━━━┩
│ttyACM0│?   │     │       │
│ttyACM1│?   │     │       │
│ttyUSB1│?   │     │       │
└───────┴────┴─────┴───────┘
```

There is a Raspberry Pi Pico 2 W attached to /dev/ttyACM1. mpremote finds it.

**Comment by Josverl** [comment]
Likely related to new tags die to the recent release, I'll look into it

**Comment by scruss** [comment]
Sorry to put you through a lot. This seems to only affect my rather old (but updated to 24.10, Python 3.12.7 ) Ubuntu box. mpflash works fine on a Raspberry Pi with Python 3.11.2

**Comment by Josverl** [comment]
No problem,

I still found and solved another missing dependency issue, so time we'll spent

**Comment by scruss** [comment]
Thanks for fixing this. 

version 1.24.8 does leave an attached CircuitPython device (a [QTPy-Knob](https://github.com/todbot/qtpy-knob) running CircuitPython v9.2.3) in an unusable state, though. I have to disconnect and reconnect the device if I run mpflash

**Comment by Josverl** [comment]
The change was related to flashing stm32 on windows, unlikely that this is related to this issue.

Mpflash does try to stop any running scripts though, so perhaps it should reset a device to return it to a running state.
